### ISSUE TITLE
Nightly test failures to investigate

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/run-aqa#24]
Now that nightlies are running as part of a recent addition of some workflows, we have to triage and clean up the runs:

https://github.com/AdoptOpenJDK/run-aqa/actions/runs/181650277

I've created https://github.com/eclipse/openj9/issues/10227 for the failures relating to that, but there are other types of failures in the nightly build that need to be looked at.

FYI @sophia-guo can you please help review some of the other types of failures seen in these nightlies?

**Comment by sophia-guo** [comment]
openj9, functional, 8|11|14, ubuntu | mac failures are related with native tests. Test against nightly build from AdoptOpenJDK, which doesn't include native libs. To avoid this I will update target to `_sanity.regular`

**Comment by sophia-guo** [comment]
hotspot, openjdk, 14, ubuntu | mac , jdk_foreign_0 failure is similar to the above comment, due to missing testimages. Will update playlist to make sure the tests belong to  `<type>native</type>`

**Comment by sophia-guo** [comment]
re https://github.com/AdoptOpenJDK/run-aqa/issues/24#issuecomment-664482494

There is only one test java/foreign/TestNative.java depends on the testimages. If we add `<type>native</type>` the whole test jdk_foreign_0 won't be able to run in run-aqa nightly run. ( though adoptOpenJDK nightly run won't be affected as target sanity.openjdk is used)

**Comment by smlambert** [comment]
hmm, we could do as Pete has done for other tests ([example](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1845)), where the individual test gets excluded, then it gets its own test target where it gets run without referencing the excludes problem list.  Not sure if this is a good pattern for the long-term though.

**Comment by sophia-guo** [comment]
TEST: java/util/Locale/LocaleCategory.java failed with jdk_util_j9: ubuntu, openj9, 11 |14
TEST: java/util/zip/ZipFile/TestCleaner.java error with jdk_util_j9, ubuntu, openj9, 11

Looking at ...
TEST: java/util/Locale/LocaleCategory.java failed in 14. 
java/util/zip/ZipFile/TestCleaner.java error, 


TEST: java/util/Locale/LocaleCategory.java failed in 14.

**Comment by smlambert** [comment]
TestCleaner has failed in other runs too, see https://github.com/eclipse/openj9/issues/8872

also see https://github.com/eclipse/openj9/issues/9042, though it was not reproducible in the report.

**Comment by sophia-guo** [comment]
Window issue related with cygwin not installed at all, need to looking into the reason.

**Comment by sophia-guo** [comment]
The tip of v1 release is https://github.com/AdoptOpenJDK/run-aqa/pull/17, which doesn't include cygwin supports. Update v1 release with master, which includes enable windows runner and https://github.com/AdoptOpenJDK/run-aqa/pull/25. 

Native tests issue and windows issue should be fixed by this new release.

**Comment by sophia-guo** [comment]
Macos, hotspot, 8, jdk_jdi failed 90, looks like all are 

```
 Target VM failed to initialize.
java.lang.NullPointerException
	at VMConnection.open(VMConnection.java:196)
	at TestScaffold.connect(TestScaffold.java:632)
	at TestScaffold.startUp(TestScaffold.java:363)
	at TestScaffold.startTo(TestScaffold.java:373)
	at TestScaffold.startToMain(TestScaffold.java:368)
	at VMDeathRequestTest.runTests(VMDeathRequestTest.java:106)
	at TestScaffold.startTests(TestScaffold.java:429)
	at VMDeathRequestTest.main(VMDeathRequestTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.NullPointerException
JavaTest Message: shutting down test

STDOUT:
ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException

```

**Comment by sophia-guo** [comment]
Ubuntu, 8, openj9, functional:
testJITServer_1 Failed:

```
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Expected an exit value of 0 or 143, got 255 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    JITServerTest
    Tests run: 6, Failures: 1, Skips: 0

```

**Comment by sophia-guo** [comment]
Ubuntu, 8, openj9, functional
cmdLineTester_SCCommandLineOptionTests_1 failed:

```
Testing: nameOption2
Test start time: 2020/07/27 21:03:15 Coordinated Universal Time
Running command: sh nameOption2.sh /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin
Time spent starting: 1 milliseconds
Time spent executing: 261 milliseconds
Test result: FAILED
 [OUT] Hello, world!
 [OUT] TEST PASSED
 [OUT] nameOption2: TEST FAILED
 [OUT] nameOption2: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "runner" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
>> Success condition was found: [Output match: TEST PASSED]
>> Failure condition was found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

Testing: nameOption4
Test start time: 2020/07/27 21:03:15 Coordinated Universal Time
Running command: sh nameOption4.sh /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin
Time spent starting: 6 milliseconds
Time spent executing: 325 milliseconds
Test result: FAILED
 [OUT] Hello, world!
 [OUT] TEST PASSED
 [OUT] nameOption4: TEST FAILED
 [OUT] nameOption4: Expected to find the cache name
 [OUT] TEST PASSED
 [ERR] JVMSHRC806I Compressed references persistent shared cache "_runner_docker" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
>> Success condition was found: [Output match: TEST PASSED]
>> Failure condition was found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

Executing command: /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/java -Xshareclasses:destroyAll


---TEST RESULTS---
Number of PASSED tests: 25 out of 27
Number of FAILED tests: 2 out of 27

---SUMMARY OF FAILED TESTS---
nameOption2
nameOption4

```

**Comment by sophia-guo** [comment]
Ubuntu | Macos, openj9, jdk11 |14 jvmnativestest_0, looks like it's native test, need to double check.

```
1) test_CallGetNanoTimeAdjustment(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: j9vmtest (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:598)
	at com.ibm.oti.jvmtests.SupportJVM.<clinit>(SupportJVM.java:30)
	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_CallGetNanoTimeAdjustment(GetNanoTimeAdjustment.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
2) test_EnsureWallClockTime(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.NoClassDefFoundError: com.ibm.oti.jvmtests.SupportJVM (initialization failure)
...
...
```

**Comment by sophia-guo** [comment]
Ubuntu,  jdk11, openj9, fucnitonal, testJITServer_0 segment fault"

```
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    JITServerTest
    Tests run: 6, Failures: 1, Skips: 0
```

**Comment by sophia-guo** [comment]
Macos, openj9, functional, jdk8:

cmdLineTester_callsitedbgddrext_openj9_0

```
Testing: Run !printallcallsites
Test start time: 2020/07/27 23:39:32 Coordinated Universal Time
Running command: /Users/runner/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/jdmpview -core j9core.dmp
Time spent starting: 17 milliseconds
Time spent executing: 487 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: Image file '/Users/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_15958922979693/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp' not found.
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: jvminit.c]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: no shared cache]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]


 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: jvminit.c]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: no shared cache]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]


---TEST RESULTS---
Number of PASSED tests: 3 out of 5
Number of FAILED tests: 2 out of 5

```

**Comment by sophia-guo** [comment]
Macos, openj9, functional, jdk8:

testSCCMLTests1_openj9_1:

```
Testing: Test 26: CMVC 168131 : Create a non persistent cache
Test start time: 2020/07/27 23:40:18 Coordinated Universal Time
Running command: "/Users/runner/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent -version
Time spent starting: 3 milliseconds
Time spent executing: 46 milliseconds
Test result: FAILED
 [ERR] JVMSHRC659E An error has occurred while opening shared memory
 [ERR] JVMSHRC336E Port layer error code = -174
 [ERR] JVMSHRC337E Platform error message: Invalid argument
 [ERR] JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings
 [ERR] JVMSHRC663I Error recovery: destroyed semaphore set with id=65537 associated with shared class cache.
 [ERR] JVMSHRC840E Failed to start up the shared cache.
 [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
 [ERR] Error: Could not create the Java Virtual Machine.
 [ERR] Error: A fatal exception has occurred. Program will exit.
>> Success condition was not found: [Output match: (java|openjdk) version]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was not found: [Output match: corrupt]
>> Failure condition was not found: [Output match: Processing dump event]


Testing: Test 28: CMVC 168131 : Re-create by failing buildid match
Test start time: 2020/07/27 23:40:18 Coordinated Universal Time
Running command: "/Users/runner/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,testBadBuildId -version
Time spent starting: 2 milliseconds
Time spent executing: 45 milliseconds
Test result: FAILED
 [ERR] JVMSHRC659E An error has occurred while opening shared memory
 [ERR] JVMSHRC336E Port layer error code = -174
 [ERR] JVMSHRC337E Platform error message: Invalid argument
 [ERR] JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings
 [ERR] JVMSHRC663I Error recovery: destroyed semaphore set with id=131073 associated with shared class cache.
 [ERR] JVMSHRC840E Failed to start up the shared cache.
 [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
 [ERR] Error: Could not create the Java Virtual Machine.
 [ERR] Error: A fatal exception has occurred. Program will exit.
>> Success condition was not found: [Output match: (java|openjdk) version]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was not found: [Output match: corrupt]
>> Failure condition was not found: [Output match: Processing dump event]

...
---TEST RESULTS---
Number of PASSED tests: 78 out of 86
Number of FAILED tests: 8 out of 86

---SUMMARY OF FAILED TESTS---
Test 26: CMVC 168131 : Create a non persistent cache
Test 28: CMVC 168131 : Re-create by failing buildid match
Test 30: CMVC 168131 : Cleanup
Test 31: CMVC 168131 : Create a non persistent cache
Test 32: CMVC 168131 : Ensure cache size is 32 MB
Test 33: CMVC 168131 : Re-create by failing buildid match
Test 34: CMVC 168131 : Ensure cache size is still 32 MB
Test 35: CMVC 168131 : Cleanup
```

**Comment by sophia-guo** [comment]
Macos, openj9, functional, jdk8::

cmdLineTester_CryptoTest_0

```
Running command: "/Users/runner/hostedtoolcache/jdk-8-openj9/1.0.0/x64/bin/java"   -Djdk.nativeCryptoTrace=true -cp "/Users/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/openssl/"openssltest.jar org.openj9.test.openssl.CryptoTest
Time spent starting: 39 milliseconds
Time spent executing: 340 milliseconds
Test result: FAILED
Output from test:
 [OUT] Crypto test COMPLETED
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
>> Success condition was not found: [Output match: using native crypto library]
>> Required condition was found: [Output match: Crypto test COMPLETED]
>> Failure condition was found: [Output match: Native crypto library load failed]
>> Failure condition was not found: [Output match: Crypto test FAILED]


---TEST RESULTS---
Number of PASSED tests: 0 out of 1
Number of FAILED tests: 1 out of 1

---SUMMARY OF FAILED TESTS---
CryptoTest
```

**Comment by sophia-guo** [comment]
Macos, openj9, functional, jdk11

SCURLClassLoaderNPTests_1

```
FindStore.FindNetUse
FindStore.FindClassfile
FindStore.FindDiffcpClassfile
JarExtensionsTests.SingleJarInManifest
JarExtensionsTests.MultipleJarsInManifests
JarExtensionsTests.SingleJarInManifest.Verify1
JarExtensionsTests.SingleJarInManifest.Verify2
JarExtensionsTests.MultipleJarsInManifests.Verify1
JarExtensionsTests.MultipleJarsInManifests.Verify2
JarExtensionsTests.SingleJarInManifestWithIndex
JarExtensionsTests.MultipleJarsInManifestsWithIndex
JarExtensionsTests.SingleJarInManifestWithIndex.Verify1
JarExtensionsTests.SingleJarInManifestWithIndex.Verify2
JarExtensionsTests.MultipleJarsInManifestsWithIndex.Verify1
JarExtensionsTests.MultipleJarsInManifestsWithIndex.Verify2
Sealed.success
Sealed.failure1
Sealed.failure2
Sealed.verify1
Sealed.verify2
NonExistJarTests.StoreWithB
NonExistJarTests.CheckForError1
NonExistJarTests.StoreWithRogueB
```

**Comment by sophia-guo** [comment]
Recorded all failure with ubuntu and macos. Will triage later.

Will wait new run with windows and see how it goes.

**Comment by sophia-guo** [comment]
Windows, jdk11, openjdk, hs|openj9:
 java/lang/ProcessBuilder/checkHandles/CheckHandles.java is a native test. Will do as same as before https://github.com/AdoptOpenJDK/run-aqa/issues/24#issuecomment-664560294

**Comment by sophia-guo** [comment]
All windows issues updated.

**Comment by sophia-guo** [comment]
Latest failures update:

- [ ]  1. TestJlmRemoteMemoryAuth_0 on build ubuntu-latest, 8, hotspot, system. 

        TestJlmRemoteMemoryAuth_0 on build ubuntu-latest, 8, hotspot, system. same behaviour on AdoptOpenJDK:
https://ci.adoptopenjdk.net/view/all/job/Test_openjdk8_hs_sanity.system_x86-64_linux/
Last successful is https://ci.adoptopenjdk.net/view/all/job/Test_openjdk8_hs_sanity.system_x86-64_linux/510/
similar issue opened AdoptOpenJDK/openjdk-tests#1903

- [ ] 2. cmdLineTester_SCCommandLineOptionTests_1  https://github.com/AdoptOpenJDK/run-aqa/issues/24#issuecomment-665111315

- [ ] 3. java/util/Locale/LocaleCategory.java on ubuntu, 11, openj9, openjdk, ubuntu

- [ ] 4. cmdLineTester_SCCommandLineOptionTests_1, 11, openj9, functional, ubuntu

- [ ]

**Comment by sophia-guo** [comment]
rerun  java/util/Locale/LocaleCategory.java on ubuntu against openj9 and hotspot in AdoptOpenJDK both showing LANG=en_US.UTF-8 and passed.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/grinder_sandbox/106/console
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/grinder_sandbox/105/console


rerun in github action, and shows LANG=en_US.UTF-8 and passed. ( ignore the action status, see the console output):
https://github.com/sophia-guo/runaqaTest/runs/1217121810?check_suite_focus=true

**Comment by sophia-guo** [comment]
All existing failures have been either fixed or addressed in separate issues. Close this now.
