### ISSUE TITLE
java/util/concurrent/forkjoin/AccessControlContext.java got `java.security.AccessControlException: access denied with linux hotspot jdk8

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#48]
java/util/concurrent/forkjoin/AccessControlContext.java got java.security.AccessControlException: access denied with a few recent linux jdk. Same for hotspot or openj9 implementation. For example : https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-02-12-32/OpenJDK8U-jdk_x64_linux_hotspot_2020-12-02-12-32.tar.gz

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-03-05-34/OpenJDK8U-jre_x64_linux_hotspot_2020-12-03-05-34.tar.gz

```
"/opt/hostedtoolcache/jdk-8-hotspot/1.0.0/x64/bin/java" -version
openjdk version "1.8.0_282-internal"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-internal-202012021720-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b03, mixed mode)
```
```
"/opt/hostedtoolcache/jdk-8-hotspot/1.0.0/x64/bin/java" -version
openjdk version "1.8.0_282-internal"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-internal-202012021720-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b03, mixed mode)
```

```
STDERR:
java.security.AccessControlException: access denied ("java.util.PropertyPermission" "java.version" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:886)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
	at java.lang.System.getProperty(System.java:719)
	at AccessControlContext.testPermission(AccessControlContext.java:42)
	at AccessControlContext$3.compute(AccessControlContext.java:78)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

```

Happened in run-aqa action and can reproduce by grinder:
https://github.com/AdoptOpenJDK/run-aqa/runs/1501099482?check_suite_focus=true

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/159/console

A latest nightly build looks fine:
https://github.com/sophia-guo/runaqaTest/runs/1513027338?check_suite_focus=true

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/158/

**Comment by sophia-guo** [comment]
Test passed with  https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-02-12-32/OpenJDK8U-jdk_x64_linux_hotspot_2020-12-02-12-32.tar.gz in https://github.com/AdoptOpenJDK/run-aqa/runs/1488766591?check_suite_focus=true, but failed in grinder https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/159/console, which probably means it's an intermittent failure. 

It did pass with latest nightly in both grinder or run-aqa. Rerun 100* in grinder in case it is an intermittent failure.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/160/console

**Comment by sophia-guo** [comment]
Run 100* with latest nightly https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/160/ test passed. So it should be an intermittent failure for a few recent jdks only.

**Comment by sophia-guo** [comment]
The failure didn't show up with recent nightly builds. Close it for now.
