### ISSUE TITLE
functional test: Jep334Tests_0 ( jdk12+) fails with hotspot jdk 15 on all github runners

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#49]
Jep334Tests_0 fails with hotspot jdk 15 on all github runners.

5 tests failed with same reason:
```
FAILED: testVarHandleDescribeConstableArray
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.describeConstableTestGeneral(Test_VarHandle.java:111)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.testVarHandleDescribeConstableArray(Test_VarHandle.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testVarHandleDescribeConstableInstanceField
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.describeConstableTestGeneral(Test_VarHandle.java:111)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.testVarHandleDescribeConstableInstanceField(Test_VarHandle.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
...

FAILED: testVarHandleDescribeConstableStaticField
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.describeConstableTestGeneral(Test_VarHandle.java:111)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.testVarHandleDescribeConstableStaticField(Test_VarHandle.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	...

FAILED: testVarHandleHashCode
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.testVarHandleHashCodeSub(Test_VarHandle.java:151)
	at org.openj9.test.java_lang_invoke.Test_VarHandle.testVarHandleHashCode(Test_VarHandle.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	...

FAILED: testVarHandleDescResolveConstantDesc
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang_invoke.Test_VarHandleDesc.resolveConstantDescTestGeneric(Test_VarHandleDesc.java:223)
	at org.openj9.test.java_lang_invoke.Test_VarHandleDesc.testVarHandleDescResolveConstantDesc(Test_VarHandleDesc.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	...


===============================================
    Jep334Tests
    Tests run: 28, Failures: 5, Skips: 0

```

https://github.com/AdoptOpenJDK/run-aqa/runs/1519924365?check_suite_focus=true

Reproduced in Adopt Grinder: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/166/

Question: Do those tests work for hotspot?

**Comment by sophia-guo** [comment]
Same failures in AdoptOpenjdk jenkins:
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk15_hs_sanity.functional_x86-64_windows/31/console
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk15_hs_sanity.functional_x86-64_linux/34/console
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk15_hs_sanity.functional_x86-64_mac/34/console

**Comment by sophia-guo** [comment]
@theresa-m do you have idea if those tests work with hotspot impl?

**Comment by theresa-m** [comment]
I ran these manually against a jdk12 hotspot build from Mar 22, 2019 just after the Java 12 release and those tests also fail so this is not a recent regression.

Since these are jcl tests ideally the two vms should both pass. I will do some more investigating to see if there's a good argument for disabling these tests.

**Comment by sophia-guo** [comment]
There may not be an easy way to disable these specific tests per impl. Probably can only disable the whole test class in playlist.xml by impl.

**Comment by theresa-m** [comment]
hotspot removed `java.lang.invoke.VarHandle` `equals` and `hashCode` implementations for Java 12. https://bugs.openjdk.java.net/browse/JDK-8215648

These tests rely on the implementation of these methods. I will open a pull request to remove `equals` and `hashCode` from OpenJ9 as well and correct the tests.

**Comment by theresa-m** [comment]
The fix has been merged https://github.com/eclipse/openj9/pull/11521

**Comment by sophia-guo** [comment]
Passed in https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/175/
and 
https://github.com/sophia-guo/runaqaTest/actions/runs/438245047
