### ISSUE TITLE
cmdLineTester_loadLibraryTests_0 fail ( jdk8, 11, 15 with hotspot on windows)

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#52]
Test is limited on windows. And fail with hotspot jdk8, 11, 15)

https://github.com/AdoptOpenJDK/run-aqa/runs/1533291962?check_suite_focus=true

```
Testing: LoadLibrary testcase with invalid paths specified in the library path list
Test start time: 2020/12/10 20:43:33 Greenwich Mean Time
Running command: C:/hostedtoolcache/windows/jdk-15-hotspot/1.0.0/x64\bin\java -Djava.library.path=".;'C:\\Program Files (x86)\\ibm\\tivoli';C:\\Users\\j9build;C:\\dev;." -cp D:/a/run-aqa/run-aqa/openjdk-tests///..//jvmtest\functional\cmdLineTests\loadLibraryTest\loadLibraryTest.jar org.openj9.test.loadLibrary.TestLoadLibrary
Time spent starting: 33 milliseconds
Time spent executing: 126 milliseconds
Test result: FAILED
Output from test:
 [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: no abcdef in java.library.path: .;'C:\\Program Files (x86)\\ibm\\tivoli';C:\\Users\\j9build;C:\\dev;.
 [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
 [ERR] 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
 [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:1893)
 [ERR] 	at org.openj9.test.loadLibrary.TestLoadLibrary.<clinit>(TestLoadLibrary.java:32)
>> Success condition was not found: [Output match: Not found in java.library.path]
>> Success condition was not found: [Output match: The specified network name is no longer available]
>> Success condition was not found: [Output match: java.lang.UnsatisfiedLinkError: Can't load abcdef]
>> Failure condition was not found: [Output match: The specified path is invalid]
>> Failure condition was not found: [Output match: Could not find or load main class Files]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: corrupt]
>> Failure condition was not found: [Output match: Processing dump event]
>> Failure condition was not found: [Output match: JVM requested Java dump]
>> Failure condition was not found: [Output match: JVM requested Snap dump]
```

Same failures in AdoptOpenjdk jenkins:
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_sanity.functional_x86-64_windows/51/console
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_sanity.functional_x86-64_windows/36/console
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk15_hs_sanity.functional_x86-64_windows/31/console

**Comment by sophia-guo** [comment]
This is a testcase issue. The failure is due to the different implementation of the  UnsatisfiedLinkError message. 

Hotspot  is like:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no abcdef in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at TestLibarary.<clinit>(TestLibarary.java:5)

```
while openj9 message is like:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: abcdef (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1745)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1696)
	at java.base/java.lang.System.loadLibrary(System.java:603)
	at TestLibarary.<clinit>(TestLibarary.java:5)
```

 We will need to  add another success case in https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/loadLibraryTest/loadLibraryTest.xml#L37

```
<output type="success" regex="no" showMatch="yes">no abcdef in java.library.path</output>
```

or disable the test with impl=hotspot

@smlambert

**Comment by smlambert** [comment]
I guess for now we must disable it.  I would like to find a way where we optimize the use of functional tests for both implementations, but that will be a major endeavour and not for us to deal with in the short-term.

**Comment by sophia-guo** [comment]
https://github.com/eclipse/openj9/issues/11470

**Comment by smlambert** [comment]
https://github.com/eclipse/openj9/pull/11471 is merged, this should be resolved.

**Comment by sophia-guo** [comment]
Yes, we should. I'd like to close the issue when the nightly jobs show the test is good. Current [nightly openj9 functional jobs fails](https://github.com/AdoptOpenJDK/run-aqa/issues/62) at compiling stage.  Not sure when it will be good. Close this for now if anything shows up we can reopen it.
