### ISSUE TITLE
jdk_math_j9_0 fails with jdk11, openj9 on window

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#60]
https://github.com/AdoptOpenJDK/run-aqa/issues/24#issuecomment-664620459jdk_math_j9_0

```
Eclipse OpenJ9 VM AdoptOpenJDK (build master-8b5b57b56, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20201212_857 (JIT enabled, AOT enabled)
OpenJ9   - 8b5b57b56
OMR      - 4c466e642
JCL      - c47c5c113f based on jdk-11.0.10+6)
...
Running jstack on process 1164
2020-12-15T21:36:47.488911100
Timeout refired 300 times
Error getting data from 1164: Exception connecting to 1164
Timeout handler interrupted: 
java.lang.InterruptedException
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:547)
	at jtreg.openj9.CoreDumpTimeoutHandler.runJstack(CoreDumpTimeoutHandler.java:83)
	at jtreg.openj9.CoreDumpTimeoutHandler.runActions(CoreDumpTimeoutHandler.java:56)
	at com.sun.javatest.regtest.TimeoutHandler.handleTimeout(TimeoutHandler.java:120)
	at com.sun.javatest.regtest.exec.ProcessCommand$2.run(ProcessCommand.java:317)
--- Timeout information end.
elapsed time (seconds): 1554.27
configuration:
STDOUT:
```

https://github.com/AdoptOpenJDK/run-aqa/runs/1552959308?check_suite_focus=true

**Comment by sophia-guo** [comment]
Looks like it's intermittent or it's fixed in latest build:
https://github.com/AdoptOpenJDK/run-aqa/runs/1572889397?check_suite_focus=true

**Comment by sophia-guo** [comment]
Continually passed. Close it.

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/run-aqa/runs/1597079936?check_suite_focus=true

happened again. reopen.

**Comment by sophia-guo** [comment]
Also happened to openj9 15 windows: https://github.com/AdoptOpenJDK/run-aqa/runs/1597080093?check_suite_focus=true

Test is TEST: java/util/regex/NegativeArraySize.java under jdk_util_j9. Same error:

```
ACTION: main -- Error. Program `C:\hostedtoolcache\windows\jdk-15-openj9\1.0.0\x64\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1556820ms).
REASON: User specified action: run main/othervm NegativeArraySize -Xms5G -Xmx5G 
TIME:   1556.823 seconds
messages:
command: main NegativeArraySize -Xms5G -Xmx5G
reason: User specified action: run main/othervm NegativeArraySize -Xms5G -Xmx5G 
Mode: othervm [/othervm specified]
Timeout information:
Running jcmd on process 4904
Error getting data from 4904: Exception connecting to 4904
Usage : jcmd <vmid> <arguments>

   -J : supply arguments to the Java VM running jcmd
   -l : list JVM processes on the local machine
   -h : print this help message

   <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools

   arguments:
      help : print the list of diagnostic commands
      help <command> : print help for the specific command
      <command> [command arguments] : command from the list returned by "help"

list JVM processes on the local machine. Default behavior when no options are specified.

NOTE: this utility might significantly affect the performance of the target JVM.
    The available diagnostic commands are determined by
    the target VM and may vary between VMs.
Running jstack on process 4904
2020-12-22T22:00:31.123360700
Timeout refired 300 times
Error getting data from 4904: Exception connecting to 4904
Timeout handler interrupted: 
java.lang.InterruptedException
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:552)
	at jtreg.openj9.CoreDumpTimeoutHandler.runJstack(CoreDumpTimeoutHandler.java:83)
	at jtreg.openj9.CoreDumpTimeoutHandler.runActions(CoreDumpTimeoutHandler.java:56)
	at com.sun.javatest.regtest.TimeoutHandler.handleTimeout(TimeoutHandler.java:120)
	at com.sun.javatest.regtest.exec.ProcessCommand$2.run(ProcessCommand.java:317)
--- Timeout information end.
elapsed time (seconds): 1556.823
configuration:
STDOUT:
Timeout refired 960 times
STDERR:
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/12/22 21:39:32 - please wait.
JVMDUMP032I JVM requested Java dump using 'D:\a\run-aqa\run-aqa\openjdk-tests\TKG\test_output_16086708803492\jdk_util_j9_0\work\scratch\javacore.20201222.213932.4904.0001.txt' in response to an event

```

**Comment by sophia-guo** [comment]
Rerun in AdoptOpenJDK looks fine. https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/179/

**Comment by sophia-guo** [comment]
Looks like both failures are intermittent and only happens to github runner environment.  Consistent to test case :
java/util/regex/NegativeArraySize.java 
java/math/BigInteger/DivisionOverflow.java
