### ISSUE TITLE
JCL_Test_SE80 failed with openj9, jdk8 on all git-hub runners

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#63]
Newly enabled Tests JCL_Test_SE80_0|1|2 by adding environment variable SPEC failed. 
https://github.com/AdoptOpenJDK/run-aqa/runs/1591270101?check_suite_focus=true

```
FAILED: test_equalsIgnoreCase
java.lang.AssertionError: Turkish 'Ä±' in middle of string lc version returned unequal to uc
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_String.test_equalsIgnoreCase(Test_String.java:599) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/jre/lib/rt.jar
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/jre/lib/rt.jar
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/jre/lib/rt.jar
	at java.lang.reflect.Method.invoke(Method.java:498) from /opt/hostedtoolcache/jdk-8-openj9/1.0.0/x64/jre/lib/rt.jar
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)

FAILED: test_regionMatches2
java.lang.AssertionError: Turkish 'Ä±' in middle of string failed comparison with different cases
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_String.test_regionMatches2(Test_String.java:1065) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/jvmtest/functional/Java8andUp/GeneralTest.jar)
	...	at org.testng.TestNG.main(TestNG.java:1323) from sun.misc.Launcher$AppClassLoader@edb22310(file:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/lib/testng.jar)


===============================================
    JCL_TEST_Java-Lang
    Tests run: 369, Failures: 2, Skips: 0
```

**Comment by sophia-guo** [comment]
Duplicate of https://github.com/eclipse/openj9/issues/11399. Will wait and see if it's fixed by next available nightly.

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/337 is not fixed.  However somehow the current nightly build we get is Jan 5, which works. Close this for now.
