### ISSUE TITLE
System test TestJlmRemoteMemoryAuth_0 failed with hotspot jdk8 on Macos

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/run-aqa#67]
System test TestJlmRemoteMemoryAuth_0 failed with hotspot jdk8 on Macos from Jan 8th.

```
CL2 stderr j> 2021/01/12 01:38:53.213   Peak usage smaller than current usage here:
CL2 stderr j> 2021/01/12 01:38:53.214   Memory Pool:              Code Cache
CL2 stderr j> 2021/01/12 01:38:53.214   Memory Type:              NON_HEAP
CL2 stderr j> 2021/01/12 01:38:53.214   Peak Usage:               init = 2555904(2496K) used = 21268800(20770K) committed = 21430272(20928K) max = 251658240(245760K)
CL2 stderr j> 2021/01/12 01:38:53.214   Current Usage:            init = 2555904(2496K) used = 21288384(20789K) committed = 21430272(20928K) max = 251658240(245760K)
CL2 stderr Exception in thread "main" java.lang.AssertionError: Peak Usage used memory smaller than Current Usage used memory
CL2 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.MemoryData.checkPeakAndCurrentMemoryUsage(MemoryData.java:521)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.MemoryData.writeData(MemoryData.java:401)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.getStatsViaServer(MemoryProfiler.java:251)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:112)
STF 01:38:53.575 - **FAILED** Process CL2 ended with exit code (1) and not the expected exit code/s (0)
STF 01:38:53.575 - Monitoring Report Summary:
```

Both in github runner and AdoptOpenjdk:
https://github.com/AdoptOpenJDK/run-aqa/runs/1684000536?check_suite_focus=true
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk8_hs_sanity.system_x86-64_mac/405/consoleFull

@lumpfish @Mesbah-Alam any idea?

**Comment by sophia-guo** [comment]
same failure on window with hotspot jdk8 on github runner from Jan8th. Though no issue in AdoptOpenJDK .

**Comment by lumpfish** [comment]
There is an issue already here: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/27. It's intermittent - both openj9 and hotspot may fail in the same way.

The test case could be tweaked to allow for a (small) discrepancy between 'current' and 'peak', but there doesn't appear to be anything wrong with the test case code.  Putting effort into increasing the failure rate locally to get some jdk developer help investigate might help understand what's going on.  It may be that 'peak' is only updated from time to time but 'current' is always correct, for instance.

**Comment by sophia-guo** [comment]
same https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.system_arm_linux/127/console
